'use-strict';

export const ADD_VACCINATION_DOSE = 'ADD_VACCINATION_DOSE';
export const REMOVE_VACCINATION_DOSE = 'REMOVE_VACCINATION_DOSE';
export const SET_PROCEDURE_DATE = 'SET_PROCEDURE_DATE';
export const SET_VACCINATION_DATE = 'SET_VACCINATION_DATE';
export const TOGGLE_VACCINATION_COMPLETION = 'TOGGLE_VACCINATION_COMPLETION';
